# Site wide configuration

title:            SimCodes
locale:           en_US
url:              


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner: Simone Hill
  name: Simone Hill
  avatar: simone_with_elephant.jpg
  bio: I used to just write. Now I code and write. Let's see how this goes.
  email: simone.hill@flatironschool.com
  disqus-shortname: 
  twitter: sim1hill
  facebook: #username
  google:
    plus: #username
    analytics: 
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
  github: sim1hill
  stackoverflow: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  xing: #username
  instagram: sim1hill
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
